# Generated by Django 4.1.5 on 2023-01-19 22:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Assignment Name', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Course Name', max_length=128)),
                ('courseCode', models.CharField(default='CCCC-1234', max_length=16)),
                ('semester', models.CharField(default='Fall', max_length=16)),
                ('year', models.IntegerField(default=1858, validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Project Name', max_length=128)),
                ('isTemplate', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Student Name', max_length=256)),
                ('email', models.CharField(default='Student Email Address', max_length=128)),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='unique_student_name_email'),
        ),
        migrations.AddField(
            model_name='project',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artGrading.assignment'),
        ),
        migrations.AddField(
            model_name='project',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artGrading.course'),
        ),
        migrations.AddField(
            model_name='project',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artGrading.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='artGrading.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='artGrading.course'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('name', 'courseCode', 'semester', 'year'), name='unique_course_name_courseCode_semester_year'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('name', 'course'), name='unique_assignment_name_course'),
        ),
    ]
