# Generated by Django 4.1.5 on 2023-01-20 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGrading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentID',
            field=models.IntegerField(default=0, unique=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
