# Generated by Django 4.1.5 on 2023-01-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGrading', '0002_student_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isTemplate',
            field=models.BooleanField(default=False),
        ),
    ]
