# Generated by Django 4.1.5 on 2023-02-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGrading', '0003_alter_project_istemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(to='artGrading.student'),
        ),
    ]
