# Generated by Django 4.1.5 on 2023-04-04 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artGrading', '0004_assignment_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='numSliders',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='numTables',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
